name: Example Workflow 05
on: [push]
jobs:
 # Sequential Jobs
  Test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is First Job triggered by a ${{ github.event_name }} event."
  Test2:
      runs-on: ubuntu-latest
      needs: Test1
      steps:
        - run: echo "This is Second Job triggered by a ${{ github.event_name }} event."
  Test3:
      runs-on: ubuntu-latest
      needs: Test2
      steps:
        - run: echo "This is Third Job triggered by a ${{ github.event_name }} event."
  Test4:
      runs-on: ubuntu-latest
      needs: Test3
      steps:
        - run: echo "This is Fourth Job triggered by a ${{ github.event_name }} event."