name: Example Workflow 11
on: [workflow_dispatch]
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - run: touch new.txt
      - run: ls -l
      - name: Upload the text file
        uses: actions/upload-artifact@v4
        with:
          name: my-file
          path: new.txt
  stage2:
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: my-file
      - run: ls -l