name: Example Workflow 04 - 2026
on: [push]
jobs:
 # Parallel jobs
  Test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo " This job was automatically triggered by a ${{ github.event_name }} event, on Test 1"
  Test2:
      runs-on: ubuntu-latest
      steps:
        - run: echo " This second job was automatically triggered by a ${{ github.event_name }} event on Test 2"
  Test3:
      runs-on: ubuntu-latest
      steps:
        - run: echo " This Third job was automatically triggered by a ${{ github.event_name }} event on Test 3"
